Plot the improvement in the solution over time.

```{r plot-progress}
p1 <- plot_progress(fit,x = "timing",y = "loglik",colors = "black",
                    add.point.every = 10,e = 1e-4) +
  guides(color = "none",fill = "none",shape = "none",
         linetype = "none",size = "none")
p2 <- plot_progress(fit,x = "timing",y = "res",colors = "black",
                    add.point.every = 10,e = 1e-4) +
  guides(color = "none",fill = "none",shape = "none",
         linetype = "none",size = "none")
plot_grid(p1,p2)
```

Create Structure plot.

```{r structure-plot}
set.seed(1)
pca_embed_method <- function (fit, ...)
  drop(pca_from_topics(fit,dims = 1))
p3 <- structure_plot(fit,grouping = samples$tissue,gap = 3,
                     colors = c("darkblue","dodgerblue","darkorange",
                                "forestgreen","limegreen","tomato","darkred",
                                "olivedrab","magenta","darkmagenta",
                                "sienna","royalblue","lightskyblue",
                                "gold","lightgray","cornflowerblue"),
                     topics = c(15,3,4,5,6,7,8,9,10,11,12,13,2,14,1,16),
                     embed_method = pca_embed_method)
```
